In [1]:
import numpy as np;

In [24]:
#Encode everything
mu_1 = np.array([[0],[0]])
mu_2 = np.array([[5]])
sigma_11 = np.array([[6, 8],[8, 13]])
sigma_12 = np.array([[5],[11]])
sigma_21 = sigma_12.T
sigma_22 = np.array([[14]])
mu = np.vstack((mu_1,mu_2))
sigma = np.vstack((np.hstack((sigma_11,sigma_12)), np.hstack((sigma_21, sigma_22))))

In [29]:
#Part A
print(np.linalg.det(sigma_11))
print(np.linalg.inv(sigma_11))

13.999999999999996
[[ 0.92857143 -0.57142857]
 [-0.57142857  0.42857143]]


In [30]:
#Part C
print(sigma_11 - sigma_12 @ np.linalg.inv(sigma_22) @ sigma_21)

[[4.21428571 4.07142857]
 [4.07142857 4.35714286]]


In [33]:
61/14

4.357142857142857

In [42]:
mu_test = mu_1[:]

In [43]:
mu_test

array([[0],
       [0]])

In [44]:
mu_1[1] = 0

In [45]:
mu_test

array([[0],
       [0]])

In [46]:
1 - sigma_12

array([[ -4],
       [-10]])

In [48]:
sigma_12*sigma_12

array([[ 25],
       [121]])

In [49]:
[x for x in sigma_12]

[array([5]), array([11])]

In [50]:
np.argmin([0, 2, 5,-3])

3

In [56]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [57]:
np.log(np.linspace(0,100,20))

/Users/Eli/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 1.66073121, 2.35387839, 2.7593435 , 3.04702557,
       3.27016912, 3.45249068, 3.60664136, 3.74017275, 3.85795578,
       3.9633163 , 4.05862648, 4.14563786, 4.22568056, 4.29978854,
       4.36878141, 4.43331993, 4.49394455, 4.55110296, 4.60517019])

In [58]:
(sigma_12 + mu_test).sum()

16